spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:tcp://localhost/~/security;MODE=MYSQL  #접속 URL
    username: sa  # 사용자 이름 (로그인 시 사용)
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true